#!/bin/sh

up=$(uptime | sed -e 's/\,.*//g' -e 's/.*up\ //g' -e 's/^\ *//g')
# check if uptime is longer than an hour, and if so pad the output
case "$up" in
*":"* ) echo "襤 $up";;
*     ) echo "襤 0:$up";;
esac

